from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# Input file
factory1 = StopWordRemoverFactory()
stopword = factory1.create_stop_word_remover()
factory2 = StemmerFactory()
stemmer = factory2.create_stemmer()
f1 = open('d1.txt', 'r')
f2 = open('d2.txt', 'r')
f3 = open('d3.txt', 'r')
f4 = open('d4.txt', 'r')
f5 = open('d5.txt', 'r')
f6 = open('d6.txt', 'r')
f7 = open('d7.txt', 'r')
f8 = open('d8.txt', 'r')
f9 = open('d9.txt', 'r')
f10 = open('d10.txt', 'r')
d1 = f1.read()
d2 = f2.read()
d3 = f3.read()
d4 = f4.read()
d5 = f5.read()
d6 = f6.read()
d7 = f7.read()
d8 = f8.read()
d9 = f9.read()
d10 = f10.read()
stop1 = stopword.remove(d1)
clean1 = stemmer.stem(stop1)
stop2 = stopword.remove(d2)
clean2 = stemmer.stem(stop2)
stop3 = stopword.remove(d3)
clean3 = stemmer.stem(stop3)
stop4 = stopword.remove(d4)
clean4 = stemmer.stem(stop4)
stop5 = stopword.remove(d5)
clean5 = stemmer.stem(stop5)
stop6 = stopword.remove(d6)
clean6 = stemmer.stem(stop6)
stop7 = stopword.remove(d7)
clean7 = stemmer.stem(stop7)
stop8 = stopword.remove(d8)
clean8 = stemmer.stem(stop8)
stop9 = stopword.remove(d9)
clean9 = stemmer.stem(stop9)
stop10 = stopword.remove(d10)
clean10 = stemmer.stem(stop10)

f1.close()
f2.close()
f3.close()
f4.close()
f5.close()
f6.close()
f7.close()
f8.close()
f9.close()
f10.close()